# ╭─────────────────────────────────ImplementationGuide-hl7.fhir.uv.RE.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.cl.minsal.snre
canonical: https://interoperabilidad.minsal.cl/fhir/ig/snre
name: Sistema Nacional De Receta Electronica
title: Sistema Nacional de receta electronica
description: Guía de Implementación para los perfiles de Receta complementarios a los de CORE Nacional, para su uso en Recete Electrónica Nacional. Esta Guía se encuentra aún en proceso de creación por lo que esta versión esta sujeta a observaciones y cambios. Aquellos implementadores que tengan acceso a ella se les sugiere desarrollar comentarios para su mejora)
status: draft # draft | active | retired | unknown
version: 0.9.5
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#CL "Chile"
publisher:
  name: Unidad de Interoperabilidad - MINSAL
  url: https://interoperabilidad.minsal.cl
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#

dependencies:
  hl7.fhir.cl.clcore: 1.8.4
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#
#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#

#parameters:
#  apply-publisher: true
#  apply-contact: true
#  show-inherited-invariants: false
#  usage-stats-opt-out: true


pages:
  index.md:
    title: Inicio
  Alcances-Objetivos.md:
    title: Objetivos
  casos.md:
    title: Casos de uso
  operaciones.md:
    title: Operaciones

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Inicio: index.html
  Objetivos: Alcances-Objetivos.html
  Actores y Casos de Uso: casos.html
  Operaciones y Terminologías: operaciones.html
  Resumen de Artefactos:
    Artefactos: artifacts.html
#  Perfiles:
#    Prescripción: StructureDefinition-RecetaPrescripcionCl.html
#    Dispensación: StructureDefinition-DispensacionMedicamentoCl.html
#    Receta: StructureDefinition-RecetaCl.html
#  Ejemplos:
#    Ejemplo Prescripción: StructureDefinition-RecetaPrescripcionCl-examples.html
#    Ejemplo Dispensación: StructureDefinition-DispensacionMedicamentoCl-examples.html
#    Ejemplo de Receta: StructureDefinition-RecetaCl-examples.html
